spring:
  datasource:
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.110.16:3306/novel?useUnicode=true&characterEncoding=UTF-8&useSSL=true

  redis:
    host: 106.14.162.109
    port: 6379
    password: lsx666
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 80